New setting "stream.initial_client_percent"
badaix/snapcast pull request #1024
Opened 2022-06-26 08:15 UTC by nis65

This resolves #910.

Testcases executed manually:

* Snapclient connects to snapserver for the first time: initial volume is 100 if not configured in `/etc/snapserver.conf`. Volume is set to configured value when set. When configuration value is invalid, initial value is set to 100 too.
* Snapclient connects **not** for the first time (i.e. client already present in `/var/lib/snapserver/server.json`): Previous volume is unchanged.

Tested successfully both on current `master` and current `develop`.

2022-07-01 08:06 UTC, badaix requested changes
Thanks! Looks great, but please add the new setting to a new config group, as in my comments.

2022-07-01 08:06 UTC, badaix commented on server/etc/snapserver.conf
> +# Volume assigned to new snapclients [percent]
Can you please create a new config section `streaming_client`?
Because this is not really related to a stream, but to a client, and there are two kinds of clients: streaming and control. 
Maybe this section will be extended later with e.g. black lists, white lists of client IPs or certificates and what not.

Also please rename the setting to `initial_volume` and keep the comment that the unit is percent, like this:

```
# streaming client options ####################################################
#
[streaming_client]

# Volume assigned to new snapclients [percent]
# Defaults to 100 if unset
#initial_volume = 100
#
###############################################################################
```

2022-07-01 08:06 UTC, badaix commented on doc/configuration.md
> +- `initial_client_percent`: 0-100 [percent]: The volume an audio client gets assigned on very first connect (i.e. client not known to snapserver yet). Defaults to 100 if unset or invalid (e.g. out of
Please change according to the requested changes for `server/etc/snapserver.conf` (below).

2022-07-01 08:06 UTC, badaix commented on server/server_settings.hpp
> +        uint16_t initialClientPercent{100};
Please add a new struct `StreamingClient` with `uint16_t initialVolume`

2022-07-01 22:59 UTC, nis65 commented
Thanks a lot for your feedback and especially for the architecture clarification. Please have another look :smile:

2022-07-02 11:21 UTC, merged

2022-07-02 11:22 UTC, badaix commented
Tack så mycket! :+1: