Disconnect from pulse temporarily while there are no chunks available
badaix/snapcast pull request #931
Opened 2021-10-19 15:06 UTC by nkvoll

Disconnect from pulseaudio when no chunk has been received for 5000 ms. (same as the alsa player).

When new chunks arrive, reconnect to pulseaudio and resume playing.

This enables the pulseaudio sink to go into an idle/suspended state for powersaving, and saves cpu cycles on the snapclient when no sound is being played.

Closes: https://github.com/badaix/snapcast/issues/927

2021-10-19 18:56 UTC, nkvoll commented
Currently it breaks when changing volume when pa is not is connected:

```Assertion 's' failed at pulse/stream.c:349, function pa_stream_get_index(). Aborting.```

2021-11-20 16:17 UTC, nickalcock commented
Seems to work for me as well, fwiw. Kind of, anyway. The output is still deeply unpleasant: see issue #942. (But this is not related to this pull: it's observable with trunk and 0.25 as well.)

2021-12-01 18:43 UTC, sibowler commented
Hi @badaix - Any thoughts of when you might get a chance to review/roll this in. I've also just moved to Pulse and hitting this issue. Apart from the ongoing logging, i found that if you stop a source whilst it's playing via pulse, the speakers will then repeat the last 0.2/0.5 secs ongoing as a kind of stutter/stuck-record type sound, which I believe is related to not closing pulse.

2021-12-08 07:52 UTC, badaix requested changes
Thanks, please check my comment

2021-12-08 07:52 UTC, badaix commented on client/player/pulse_player.cpp
> +            this->connect();
`connect()` can throw an exception, that must be caught here, similar to alsa:

```
try
{
   LOG(INFO, LOG_TAG) << "Chunk available, reconnecting to pulse\n"
   connect();
}
catch (const std::exception& e)
{
   LOG(ERROR, LOG_TAG) << "Exception while connecting to pulse: " << e.what() << endl;
   disconnect();
   chronos::sleep(100);
}
```
Also some members might be initialized in `connect()`, I think a call to `disconnect()` should do the necessary cleanup.

2021-12-09 12:35 UTC, badaix commented on client/player/pulse_player.cpp
> +            this->connect();
I will add it

2021-12-09 12:36 UTC, merged

2021-12-09 12:36 UTC, badaix commented
Thanks!